services:
  crypto-tracker-app:
    build: .
    ports:
      - '3000:3000'
    env_file:
      - .env
    environment:
      NEXT_PUBLIC_COINGECKO_API: ${NEXT_PUBLIC_COINGECKO_API}
    volumes:
      - .:/app
    networks:
      - crypto_tracker_network

networks:
  crypto_tracker_network:
    driver: bridge
